SET TIMEZONE TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE rustdb TO admin;
CREATE TABLE notes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator TEXT NOT NULL,
    note TEXT NOT NULL,
    ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
INSERT INTO notes
    (creator, note, ts)
VALUES
    ('Alice', 'Hello, world!', '2021-11-25 19:31:38'),
    ('Bob', 'Lorem ipsum', '2021-11-25 21:11:06'),
    ('Alice', 'Fear is the mind killer', '2021-11-26 08:01:46');