[package]
name = "docker_test"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
diesel = { version = "1.4.0", features = ["chrono", "postgres"] }
rocket = "0.4.0"
serde = "1.0"
serde_json = "1.0"
dotenv = "0.15"
anyhow = "1.0"

[dev-dependencies]
diesel_cli = "1.4"